name: sp_psro
channels:
  - menpo
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cmake=3.18.2
  - cpuonly=1.0
  - cudatoolkit=11.1.1
  - cudnn=8.2.1.32
  - expat=2.4.2
  - ffmpeg=4.3
  - freetype=2.10.4
  - future=0.18.2
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - jbig=2.1
  - jpeg=9d
  - kernel-headers_linux-64=2.6.32
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - libsanitizer=11.2.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuv=1.42.0
  - libwebp-base=1.2.1
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - magma=2.5.4
  - mkl=2021.4.0
  - nccl=2.11.4.1
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.0
  - osmesa=12.2.2.dev
  - pip=21.3.1
  - python=3.8.12
  - python_abi=3.8
  - pytorch=1.9.0
  - pytorch-gpu=1.9.0
  - pytorch-mutex=1.0
  - readline=8.1
  - rhash=1.4.1
  - setuptools=60.5.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.37.0
  - sysroot_linux-64=2.12
  - tbb=2021.5.0
  - tk=8.6.11
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - typing_extensions=4.0.1
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.1
  - pip:
    - absl-py==0.11.0
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - async-timeout==3.0.1
    - atari-py==0.2.9
    - attrs==21.2.0
    - backcall==0.2.0
    - bayesian-optimization==1.2.0
    - beautifulsoup4==4.9.3
    - bleach==3.3.1
    - blessings==1.7
    - cachetools==4.2.2
    - certifi==2021.10.8
    - cffi==1.14.6
    - chardet==4.0.0
    - click==8.0.1
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - colorful==0.5.4
    - contextlib2==21.6.0
    - contextvars==2.4
    - cvxopt==1.2.7
    - cycler==0.10.0
    - cython==0.29.24
    - decorator==5.0.9
    - deepdiff==5.5.0
    - deepdish==0.3.6
    - defusedxml==0.7.1
    - dm-env==1.5
    - dm-tree==0.1.5
    - entrypoints==0.3
    - fasteners==0.16.3
    - filelock==3.0.12
    - flatbuffers==2.0
    - gast==0.5.3
    - glfw==2.1.0
    - google==3.0.0
    - google-api-core==1.31.0
    - google-auth==1.32.1
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - googleapis-common-protos==1.53.0
    - gpustat==0.6.0
    - grpcio==1.35.0
    - grpcio-tools==1.35.0
    - gym==0.18.0
    - gym-minigrid==1.0.2
    - h5py==3.6.0
    - hiredis==2.0.0
    - hyperopt==0.2.5
    - idna==2.10
    - idna-ssl==1.1.0
    - imageio==2.9.0
    - immutabledict==2.2.1
    - immutables==0.15
    - importlib-metadata==4.6.1
    - ipykernel==5.5.5
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - libclang==13.0.0
    - llvmlite==0.36.0
    - lockfile==0.12.2
    - lz4==3.1.3
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - ml-collections==0.1.1
    - msgpack==1.0.2
    - multidict==5.1.0
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5
    - notebook==6.4.0
    - numba==0.53.1
    - numexpr==2.7.3
    - numpy==1.22.2
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.1
    - opencensus==0.7.13
    - opencensus-context==0.1.2
    - opencv-python==4.5.1.48
    - opencv-python-headless==4.3.0.36
    - opt-einsum==3.3.0
    - ordered-set==4.0.2
    - packaging==21.0
    - pandas==1.1.5
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - plotly==4.14.0
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.19
    - protobuf==3.14.0
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - py-spy==0.3.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygame==2.1.2
    - pyglet==1.5.0
    - pygments==2.9.0
    - pyopengl==3.1.5
    - pyparsing==2.4.7
    - pyreap==0.9.1
    - pyrsistent==0.18.0
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - pyzmq==22.1.0
    - qtconsole==5.1.1
    - qtpy==1.9.0
    - ray==1.0.1.post1
    - redis==3.4.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.7.2
    - scikit-learn==0.24.1
    - scipy==1.5.4
    - seaborn==0.11.2
    - send2trash==1.7.1
    - soupsieve==2.2.1
    - tables==3.6.1
    - tabulate==0.8.9
    - termcolor==1.1.0
    - terminado==0.10.1
    - testpath==0.5.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==2.2.0
    - torchsummary==1.5.1
    - tornado==6.1
    - tqdm==4.62.2
    - traitlets==4.3.3
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.13.3
    - yarl==1.6.3
    - zipp==3.5.0
    - tensorboardX==2.5
    - tensorboard

